# Generated by Django 5.2.7 on 2025-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualuser',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
