# Generated by Django 5.2.7 on 2025-11-14 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_audiorecording_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='audio_file',
            field=models.FileField(upload_to='recordings/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.CreateModel(
            name='ExperimentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intended_reaction', models.CharField(blank=True, max_length=255, null=True)),
                ('catalyst_id', models.CharField(blank=True, max_length=50, null=True)),
                ('catalyst_composition', models.CharField(blank=True, max_length=255, null=True)),
                ('electrode_material', models.CharField(blank=True, max_length=255, null=True)),
                ('electrode_area', models.FloatField(blank=True, null=True)),
                ('catalyst_loading', models.FloatField(blank=True, null=True)),
                ('catalyst_morphology', models.CharField(blank=True, max_length=255, null=True)),
                ('catalyst_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('electrolyte', models.CharField(blank=True, max_length=255, null=True)),
                ('nitrogen_purging_time', models.IntegerField(blank=True, null=True)),
                ('electrolyte_pH', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('reference_electrode', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('cycles', models.IntegerField(blank=True, null=True)),
                ('potential_range', models.CharField(blank=True, max_length=50, null=True)),
                ('ir_compensation', models.TextField(blank=True, null=True)),
                ('rhe_conversion', models.TextField(blank=True, null=True)),
                ('initial_conditioning', models.CharField(blank=True, max_length=50, null=True)),
                ('current_density_reported', models.CharField(blank=True, max_length=255, null=True)),
                ('forward_scan_note', models.TextField(blank=True, null=True)),
                ('triplicate_measurements', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_electrode_testing', models.TextField(blank=True, null=True)),
                ('article_doi', models.CharField(blank=True, max_length=255, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('field_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_entries', to='backend_app.uploadedfile')),
            ],
            options={
                'db_table': 'ExperimentMetadata',
            },
        ),
    ]
