# Generated by Django 5.2.7 on 2025-11-15 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_alter_audiorecording_audio_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experimentmetadata',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='experimentmetadata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentmetadata',
            name='virtual_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_uploaded', to='backend_app.virtualuser'),
        ),
        migrations.CreateModel(
            name='ExperimentDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('field_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='backend_app.experimentmetadata')),
            ],
            options={
                'db_table': 'ExperimentDescription',
            },
        ),
        migrations.CreateModel(
            name='ExperimentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='backend_app.experimentmetadata')),
            ],
            options={
                'db_table': 'ExperimentFolder',
            },
        ),
        migrations.CreateModel(
            name='ExperimentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='experiment_data/')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('field_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backend_app.experimentfolder')),
            ],
            options={
                'db_table': 'ExperimentFile',
            },
        ),
        migrations.DeleteModel(
            name='AudioRecording',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
