# Generated by Django 5.2.7 on 2025-11-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_remove_uploadedfile_user_and_more'),
    ]

    operations = [
    ]
