# Generated by Django 5.2.7 on 2025-11-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_auto_20251115_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdescription',
            name='metadata',
        ),
        migrations.AddField(
            model_name='experimentdescription',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='backend_app.experimentfile'),
        ),
    ]
