# Generated by Django 5.2.7 on 2025-11-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_remove_experimentdescription_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdescription',
            name='description',
        ),
        migrations.AddField(
            model_name='experimentdescription',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='experiment_audio/'),
        ),
    ]
