# Generated by Django 5.2.7 on 2026-06-24 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_remove_experimentdescription_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualuser',
            old_name='consent',
            new_name='author_consent',
        ),
        migrations.RemoveField(
            model_name='virtualuser',
            name='session_id',
        ),
        migrations.AddField(
            model_name='experimentdescription',
            name='audio_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experimentdescription',
            name='audio_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdescription',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='cookie_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='participant_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='recovery_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='session_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('participate', models.BooleanField(default=False)),
                ('audio_consent', models.BooleanField(default=False)),
                ('consent_version', models.CharField(default='v1.0', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('field_created', models.DateTimeField(auto_now_add=True)),
                ('virtual_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='backend_app.virtualuser')),
            ],
            options={
                'db_table': 'ConsentRecord',
            },
        ),
    ]
