# Generated by Django 5.2.7 on 2026-05-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_remove_experimentdescription_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualuser',
            name='consent',
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('participate', models.BooleanField(default=False)),
                ('audio_consent', models.BooleanField(default=False)),
                ('ai_processing_consent', models.BooleanField(default=False)),
                ('publish_consent', models.BooleanField(default=False)),
                ('author_consent', models.BooleanField(default=False)),
                ('consent_version', models.CharField(default='v1.0', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('field_created', models.DateTimeField(auto_now_add=True)),
                ('virtual_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='backend_app.virtualuser')),
            ],
            options={
                'db_table': 'ConsentRecord',
            },
        ),
    ]
