# Generated by Django 5.2.7 on 2026-06-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_rename_consent_virtualuser_author_consent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualuser',
            name='session_saved',
        ),
        migrations.AddField(
            model_name='experimentfolder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentfolder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='cookie_session',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='virtualuser',
            name='participant_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
    ]
