# Generated by Django 5.2.7 on 2026-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_remove_virtualuser_session_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmetadata',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
